# YAML configuration file for Docker Compose version 3.8
version: '3.8'

# Define services
services:

  # Database service using PostgreSQL image
  database:
    image: postgres:latest  # Use the latest PostgreSQL image from Docker Hub
    environment:
      POSTGRES_DB: demodb  # Define the name of the database
      POSTGRES_USER: user    # Define the username for accessing the database
      POSTGRES_PASSWORD: password  # Define the password for the user
    ports:
      - "5432:5432"  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL

  # Backend service
  backend:
    build: .  # Build the Docker image using the Dockerfile in the current directory
    ports:
      - "3333:3000"  # Forward the container's port 3333 to the host machine's port 3333 for accessing the backend service
    depends_on:
      - database  # Ensure that the backend service starts after the database service is up and running
    env_file:
      - .env  # Load environment variables from the .env file in the current directory